let data = [
  {
    id: 1,
    title: "Modern Studio Apartment",
    location: "Lucknow",
    type: "Apartment",
    price: "1200",
    area: "500",
    image: "https://example.com/images/apartment1.jpg",
    availableFrom: "2023-09-01",
    contact: {
      name: "John Doe",
      email: "johndoe@example.com",
      phone: "123-456-7890",
    },
  },
  {
    id: 2,
    title: "Spacious Family Home",
    location: "Bijnor",
    type: "House",
    price: "2500",
    area: "1800",
    image: "https://example.com/images/house1.jpg",
    availableFrom: "2023-10-15",
    contact: {
      name: "Jane Smith",
      email: "janesmith@example.com",
      phone: "987-654-3210",
    },
  },
  {
    id: 3,
    title: "Luxury Penthouse",
    location: "Mirzapur",
    type: "Penthouse",
    price: "4500",
    area: "2000",
    image: "https://example.com/images/penthouse1.jpg",
    availableFrom: "2023-09-15",
    contact: {
      name: "Michael Johnson",
      email: "michaeljohnson@example.com",
      phone: "555-123-4567",
    },
  },
  {
    id: 4,
    title: "Charming Townhouse",
    location: "Delhi",
    type: "Townhouse",
    price: 1800,
    area: 1500,
    image: "https://example.com/images/townhouse1.jpg",
    availableFrom: "2023-09-10",
    contact: {
      name: "Sarah Johnson",
      email: "sarah@example.com",
      phone: "555-987-6543",
    },
  },
  {
    id: 5,
    title: "Cozy Cottage",
    location: "Bangalore",
    type: "Cottage",
    price: 900,
    area: 800,
    image: "https://example.com/images/cottage1.jpg",
    availableFrom: "2023-09-05",
    contact: {
      name: "David Smith",
      email: "david@example.com",
      phone: "123-555-7890",
    },
  },
  {
    id: 6,
    title: "Urban Loft",
    location: "Pune",
    type: "Loft",
    price: 2800,
    area: 1200,
    image: "https://example.com/images/loft1.jpg",
    availableFrom: "2023-09-20",
    contact: {
      name: "Emily Brown",
      email: "emily@example.com",
      phone: "987-333-2222",
    },
  },
  {
    id: 7,
    title: "Modern Condo",
    location: "Lucknow",
    type: "Apartment",
    price: 1400,
    area: 600,
    image: "https://example.com/images/condo1.jpg",
    availableFrom: "2023-09-08",
    contact: {
      name: "Amanda Lee",
      email: "amanda@example.com",
      phone: "555-789-4561",
    },
  },
  {
    id: 8,
    title: "Quaint Duplex",
    location: "Delhi",
    type: "House",
    price: 2400,
    area: 1600,
    image: "https://example.com/images/duplex1.jpg",
    availableFrom: "2023-09-12",
    contact: {
      name: "Robert Wilson",
      email: "robert@example.com",
      phone: "123-777-8888",
    },
  },
  {
    id: 9,
    title: "Chic Studio Loft",
    location: "Mumbai",
    type: "Loft",
    price: 1600,
    area: 700,
    image: "https://example.com/images/loft2.jpg",
    availableFrom: "2023-09-15",
    contact: {
      name: "Sophia Davis",
      email: "sophia@example.com",
      phone: "987-444-5555",
    },
  },
  {
    id: 10,
    title: "Modern City Apartment",
    location: "Mirzapur",
    type: "Apartment",
    price: 1300,
    area: 550,
    image: "https://example.com/images/apartment2.jpg",
    availableFrom: "2023-09-18",
    contact: {
      name: "Alex Martinez",
      email: "alex@example.com",
      phone: "555-123-7890",
    },
  },
  {
    id: 11,
    title: "Cozy Suburban Home",
    location: "Delhi",
    type: "House",
    price: 2300,
    area: 1700,
    image: "https://example.com/images/house2.jpg",
    availableFrom: "2023-09-25",
    contact: {
      name: "Olivia Anderson",
      email: "olivia@example.com",
      phone: "123-555-6789",
    },
  },
  {
    id: 12,
    title: "Industrial Loft Space",
    location: "Bijnor",
    type: "Loft",
    price: 1500,
    area: 800,
    image: "https://example.com/images/loft3.jpg",
    availableFrom: "2023-10-01",
    contact: {
      name: "William Turner",
      email: "william@example.com",
      phone: "987-666-3333",
    },
  },
  {
    id: 13,
    title: "Urban Studio Apartment",
    location: "Pune",
    type: "Apartment",
    price: 1250,
    area: 600,
    image: "https://example.com/images/apartment3.jpg",
    availableFrom: "2023-10-05",
    contact: {
      name: "Daniel Rivera",
      email: "daniel@example.com",
      phone: "555-789-1234",
    },
  },
  {
    id: 14,
    title: "Classic Townhouse",
    location: "Chandigarh",
    type: "Townhouse",
    price: 1850,
    area: 1400,
    image: "https://example.com/images/townhouse2.jpg",
    availableFrom: "2023-10-10",
    contact: {
      name: "Sophie Clark",
      email: "sophie@example.com",
      phone: "123-456-7891",
    },
  },
  {
    id: 15,
    title: "Rural Retreat",
    location: "Bangalore",
    type: "Cottage",
    price: 950,
    area: 900,
    image: "https://example.com/images/cottage2.jpg",
    availableFrom: "2023-10-15",
    contact: {
      name: "Liam Walker",
      email: "liam@example.com",
      phone: "987-654-3210",
    },
  },
  {
    id: 16,
    title: "Modern Townhome",
    location: "Pune",
    type: "Townhouse",
    price: 1750,
    area: 1300,
    image: "https://example.com/images/townhouse3.jpg",
    availableFrom: "2023-10-20",
    contact: {
      name: "Emma Scott",
      email: "emma@example.com",
      phone: "555-123-4567",
    },
  },
  {
    id: 17,
    title: "Luxury Condo",
    location: "Lucknow",
    type: "Apartment",
    price: 2200,
    area: 900,
    image: "https://example.com/images/condo2.jpg",
    availableFrom: "2023-10-25",
    contact: {
      name: "Noah Green",
      email: "noah@example.com",
      phone: "123-456-7890",
    },
  },
  {
    id: 18,
    title: "Vintage Cottage",
    location: "Delhi",
    type: "Cottage",
    price: 850,
    area: 800,
    image: "https://example.com/images/cottage3.jpg",
    availableFrom: "2023-10-30",
    contact: {
      name: "Ava Turner",
      email: "ava@example.com",
      phone: "555-987-6543",
    },
  },
];

export default data;
